### ISSUE TITLE
consider showing social sharing icons by default

### ISSUE THREAD

**Issue by caxy4** [thinkshout/ocean-outcomes#11]
we might get more shares this way - people tend to associate social media icons with sharing and i'm not sure the "share" button with the arrow has the same effect

example here: http://stage.oceanoutcomes.org.s3-website-us-east-1.amazonaws.com/2014/09/news-item-4/

**Comment by caxy4** [comment]
@MadouPDX thoughts on this?

**Comment by pbroderick** [comment]
I agree with you @caxy4 - i think it also looks better with the social media icons expanded below the hero image

**Comment by marcimarshall** [comment]
This is done.
