### ISSUE TITLE
text coming from variables does not support markdown

### ISSUE THREAD

**Issue by caxy4** [thinkshout/ocean-outcomes#8]
to fix this we have to ensure text coming from any variables is piped through the markdownify filter in templates

one example of this is that bios on staff pages do not support markdown
the fix...
```
- data-title="{{person.name}}" data-description="{{person.bio}}"
+ data-title="{{person.name}}" data-description="{{person.bio | markdownify}}"
```

**Comment by mshaver** [comment]
Closed with commit 7af09ada2eded492e571217657c014cd72c1b30e
